### ISSUE TITLE
When I attempt to open a function I get "The filename or extension is too long"

### ISSUE THREAD

**Issue by teedty1** [revmischa/sublime-awslambda#1]
This function was working perfectly.  I can open other functions, but this one throws this error every time now.

DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/user/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/user/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/user/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.0869053
startup time: 0.120905
first paint time: 0.124905
first paint time: 0.125905
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-boto3
reloading plugin 0_package_control_loader.50-requests
reloading plugin AWS Lambda.awslambda
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2016-11-18 16:09:44, next run at 2016-11-18 17:09:44 or after
created temporary directory c:\users\user\appdata\local\temp\tmpguuilh
Traceback (most recent call last):
  File "awslambda in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\AWS Lambda.sublime-package", line 291, in selected_cb
  File "awslambda in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\AWS Lambda.sublime-package", line 169, in download_function
  File "awslambda in C:\Users\user\AppData\Roaming\Sublime Text 3\Installed Packages\AWS Lambda.sublime-package", line 183, in extract_zip_url
  File "./python3.3/zipfile.py", line 1234, in extractall
  File "./python3.3/zipfile.py", line 1222, in extract
  File "./python3.3/zipfile.py", line 1281, in _extract_member
FileNotFoundError: [WinError 206] The filename or extension is too long: 'c:\\users\\user\\appdata\\local\\temp\\tmpguuilh\\users\\user\\appdata\\local\\temp\\tmpjhtvoe\\users\\user\\appdata\\local\\temp\\tmplsvgw1\\users\\user\\appdata\\local\\temp\\tmp9_ocub\\users\\user\\appdata\\local\\temp\\tmp6dn7pv\\users'

**Comment by revmischa** [comment]
Is there a possibility that the zip contains a recursive link inside?

**Comment by teedty1** [comment]
No... it is just a plain python function.  There are no files in the Lambda function, I originally built it in the Lambda editor.  I was able to edit it in your plugin before, but then I guess maybe I opened it one too many times?

**Comment by teedty1** [comment]
I ended up having to delete the function and re-create it.  Somehow the that long path got embedded into the function definition so when it tried to unzip the package it freaked out.  You've created a great product!  It makes my life so much easier.

**Comment by revmischa** [comment]
Strange. Patches welcome!
