### ISSUE TITLE
Doesn't load on Windows. Creates repetetive folder structure

### ISSUE THREAD

**Issue by PeterTNguyen** [revmischa/sublime-awslambda#2]
Firstly, great plugin! Very thankful that something like this exists so I don't have to use Eclipse or something like that. I mainly use this on OSX, but when I switch to windows I have the following error. The files are downloaded and unzipped to (C:\Users\nguye\AppData\Local\Temp\tmpkq8x0t) and also there's an empty directory at (C:\Users\nguye\AppData\Local\Temp\tmpkq8x0t\var\folders\8k\w66ftmlx4sj5tvw7q6pmzxtw0000gn\T\tmpmdgjy9\var\folders\8k\w66ftmlx4sj5tvw7q6pmzxtw0000gn\T\tmpi9q38f\var\folders\8k\w66ftmlx4sj5tvw7q6pmzxtw0000gn\T\tmpm1q9ts\var\folders\8k). It's just for this particular AWS lambda function and doesn't occur for the other ones for some reason.

Sublime console:
created temporary directory c:\users\nguye\appdata\local\temp\tmpkq8x0t
Traceback (most recent call last):
  File "awslambda in C:\Users\nguye\AppData\Roaming\Sublime Text 3\Installed Packages\AWS Lambda.sublime-package", line 291, in selected_cb
  File "awslambda in C:\Users\nguye\AppData\Roaming\Sublime Text 3\Installed Packages\AWS Lambda.sublime-package", line 169, in download_function
  File "awslambda in C:\Users\nguye\AppData\Roaming\Sublime Text 3\Installed Packages\AWS Lambda.sublime-package", line 183, in extract_zip_url
  File "./python3.3/zipfile.py", line 1234, in extractall
  File "./python3.3/zipfile.py", line 1222, in extract
  File "./python3.3/zipfile.py", line 1281, in _extract_member
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\nguye\\appdata\\local\\temp\\tmpkq8x0t\\var\\folders\\8k\\w66ftmlx4sj5tvw7q6pmzxtw0000gn\\T\\tmpmdgjy9\\var\\folders\\8k\\w66ftmlx4sj5tvw7q6pmzxtw0000gn\\T\\tmpi9q38f\\var\\folders\\8k\\w66ftmlx4sj5tvw7q6pmzxtw0000gn\\T\\tmpm1q9ts\\var\\folders\\8k\\w66ftmlx4sj5tvw7q6pmzxtw0000gn'

**Comment by revmischa** [comment]
Is this the same issue in https://github.com/revmischa/sublime-awslambda/issues/1 ?
Do you have any recursive directory links in it?

**Comment by PeterTNguyen** [comment]
Ah yes, I seem to have found my issue. It did have recursive links in it and was similar to Issue #1. When I was initially testing your plugin and figuring out how to add multiple files, I added a file to a subdirectory and that got wrapped up into the zip. I removed it from the folder structure and zip and seemed to fix the problem. Thanks.

**Comment by revmischa** [comment]
Since this is likely to come up again maybe you'd like to submit a patch to prevent this? I don't have windows.
