### ISSUE TITLE
AWS credentials not found

### ISSUE THREAD

**Issue by DaKoTTS** [revmischa/sublime-awslambda#7]
Hi,

i am using cygwin on windows and I have configured my .aws as well as my .boto credential files there. How can I tell sublime to use it with ur plugin? It just sais "AWS credentials not found. Please follow...". Can't find any setup or user config files for the sublime-awslambda.

thx,
Daniel

**Comment by revmischa** [comment]
That should be all you need if they're in what the sublime boto3 plugin thinks is your home directory. If you're running sublime in windows it most likely has nothing to do with your cygwin environment.

**Comment by DaKoTTS** [comment]
u were right, using sublime out of cygwin solved the problem :)

THX 4 the fast help and thx for the awsome addon
