### ISSUE TITLE
Installing package AWS Lambda.... never completes

### ISSUE THREAD

**Issue by rmurillo21** [revmischa/sublime-awslambda#9]
Hello,

In the Sublime3 status bar it says:

**Installing package AWS Lambda [  =  ]**

But it never completes. I am on Windows 10.

I have restarted the editor, also installed other packages and they installed ok.

I did see something about a Boto 3 dependency,  so I am suspecting it got hung there?

Could you suggest how to check the issue?

Thanks

**Comment by revmischa** [comment]
Sorry to hear that. You can try looking in the console under view->console and see if there are errors there.

**Comment by rmurillo21** [comment]
Thanks for the help - it is stuck here in the console:

Package Control: The dependency 'boto3' is not currently installed; installing...

Can I install that manually?

**Comment by rmurillo21** [comment]
Just noticed this also in the console:

  File "package_control.loader in C:\Users\rodm\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 442, in do_swap
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\rodm\\AppData\\Roaming\\Sublime Text 3\\Installed Packages\\0_package_control_loader.sublime-package'

Is that the issue?

**Comment by revmischa** [comment]
The dependencies are managed automatically by the package manager. I'm not sure what that error is, sounds like a problem with Sublime Package Control
You could check for it here or file a ticket - https://github.com/wbond/package_control/issues

**Comment by revmischa** [comment]
I don't have Windows so I can't test myself, sorry. PRs welcome

**Comment by rmurillo21** [comment]
I'll check with them thanks.
